spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: testtest55
  jpa:
    hibernate:
      ddl-auto: validate
    show:
      sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

sites:
  - url: https://volochek.life
    name: Вышний Волочёк
  - url: https://dimonvideo.ru
    name: Димон-видео.ру
  - url: https://www.lutherancathedral.ru
    name: Собор Петра и Павла


user-agent: Helicon Search Engine 1.0.0
referer: http://www.google.com
web-interface-path: /admin

logging:
  level:
    root: INFO
    com:
      search: INFO
    org:
      hibernate: ERROR





#spring.datasource.url=jdbc:mysql://localhost:3306/buysell?serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=testtest55
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show.sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect